### ISSUE TITLE
github actions

### ISSUE THREAD

**Issue by petersim1** [petersim1/blackjack-api#8]
Add github actions for managing deployments on `main` actions.
For example, this should work for deploying to prod via Fly.io

```
name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```
